speaker diarization and identification
linto-ai/linto-diarization pull request #33
Opened 2024-04-17 15:10 UTC by wghezaiel

2024-04-17 17:41 UTC, Jeronymous reviewed
Can you provide a little "how to" to describe the new feature.

How a speaker is identified? can it be with several audio files? when is the "signature of the speaker" (speaker embedding) pre-computed?

2024-04-17 17:41 UTC, Jeronymous commented on simple/diarization/processing/simple_diarizer/simple_diarizer/diarizer.py
> +        voices_box="/usr/src/app/diarization/processing/simple_diarizer/voices_ref"
Is it possible to pass this path as an argument of this function?
The value should could set from an environment variable.

Also at the start of this function, there should be some checks:
- does this folder exist?
- do all the given speaker names correspond to existing files?

2024-04-17 17:41 UTC, Jeronymous commented on simple/diarization/processing/simple_diarizer/simple_diarizer/speaker_recognition.py
> +                except:
never a "try ... except (without specific expection name) ... pass"

Here I don't see a reason to keep this try.

try has to be used very carefully.
only when it's needed.
to catch a given class of exceptions and behave accordingly, or catch an error message, log it and throw ...

2024-04-17 17:41 UTC, Jeronymous commented on simple/diarization/processing/simple_diarizer/simple_diarizer/speaker_recognition.py
> +                print(voice_file)
It looks like a debug print to remove.

If something has to be printed, better to use a log mechanism

2024-04-17 17:41 UTC, Jeronymous commented on simple/diarization/processing/simple_diarizer/simple_diarizer/speaker_recognition.py
> +    Id_count = defaultdict(int)
please use "lower_case" for local variables in python : `id_count` instead of `Id_count`

(and "CamelCase" are for classes in python)

2024-04-17 20:05 UTC, damienlaine commented on simple/diarization/processing/simple_diarizer/simple_diarizer/diarizer.py
> +        voices_box="/usr/src/app/diarization/processing/simple_diarizer/voices_ref"
ArgumentParser can get imported, use relevant argument for VoiceBox Folders. Might default for : an ENV (if set) otherwise a relative path that should get documented and used as a mount when running in container.

2024-04-17 20:18 UTC, damienlaine commented on simple/diarization/processing/simple_diarizer/simple_diarizer/speaker_recognition.py
> +    limit = 60
Limit what ? (Well, seconds of audio). Relevant comments missing

2024-04-17 20:29 UTC, damienlaine commented on simple/diarization/processing/simple_diarizer/main.py
I guess the "speaker_name" candidates voice samples must be a list of Ids

2024-04-17 21:00 UTC, damienlaine requested changes

2024-04-17 21:09 UTC, damienlaine commented on document/swagger.yml
The SQLite database thingy is a good way to go. Also make sure to store the single db file within a easily mountable volume of course as diarization workers might spread over cluster.
Concurrent writes / read are greatly supported in any scenario multiprocessing, threads..

Make sure to use 
    def get_conn(self):
        conn = sqlite3.connect(self.db_path)
        
And conn = self.get_conn() ... conn.close() on every model method calls.

2024-04-17 21:18 UTC, damienlaine commented on document/swagger.yml
Of course, a wildcard would trigger speaker identification towards all candidates.
Another great feature would be to define a range of speaker candidate ids to use ([1-5], [9-11])

2024-04-18 20:06 UTC, wghezaiel commented on simple/diarization/processing/simple_diarizer/simple_diarizer/diarizer.py
> +        voices_box="/usr/src/app/diarization/processing/simple_diarizer/voices_ref"
Corrected by adding -v voices_ref/:/usr/src/app/voices_ref

2024-04-24 14:48 UTC, wghezaiel commented
- List of candidate speaker has this format [1, 2, {"start": 7, "end": 9}, 12]
- voice_ref is composed by audio file for each speaker and SQLITE "speakers_database"
- for UNKNOWN speaker, we keep clustering label "spk1"
- tested with meeting_RAP_1.wav (4spk) and meeting_RAP_2.wav(5spk)
[voices_ref.zip](https://github.com/linto-ai/linto-diarization/files/15096095/voices_ref.zip)

2024-04-24 15:35 UTC, damienlaine commented on simple/Dockerfile
I guess sqlite3 install is not mandatory
import sqlite3 is enough.

2024-04-24 15:46 UTC, damienlaine commented on http_server/ingress.py
Wrong way of doing things :

- Use a try / catch and finaly for accessing the sqlite db
- Check if the query returned a result before attempting to access the first element (duh !)
- Sanitize inputs. "%s" can lead to injecting stuff in your request
- Avoir looping a for SELECT unique items. Prefer using a IN clause

Something like :

try:
    placeholders = ','.join('?' for unused in speakers)
    query = "SELECT Name FROM Speaker_names WHERE id IN ({})".format(placeholders)
    c.execute(query, speakers)
    speakers_list = [item[0] for item in c.fetchall()]

finally:
    conn.close()

2024-09-10 08:10 UTC, merged