Speaker Identification refactoring
linto-ai/linto-diarization pull request #46
Opened 2024-10-29 11:30 UTC by Jeronymous

2024-10-29 14:48 UTC, Jeronymous commented on identification/speaker_identification.py
@htagourti I cannot see the diff on speaker_identification.py (which is at the core of the refactoring).
Maybe because the file was renamed ?
Or because you modified everything ?

2024-10-29 15:37 UTC, htagourti commented on identification/speaker_identification.py
Yes I renamed the file

2024-10-29 16:17 UTC, damienlaine requested changes
Please make sure that qdrant is reachable before starting up operations.
Check entrypoint and wait-for-it.sh. We do not use docker compose in deployments and cannot ensure that qdrant will run before diarization.

2024-10-30 14:30 UTC, damienlaine approved these changes

2024-10-30 16:16 UTC, Jeronymous commented on identification/speaker_identify.py
> +            print("NOCOMMIT", speakers_spec, speakers_spec and (speakers_spec == "*"), self._get_db_speaker_names())
You can remove this print that should not have been commited
(I recognize that tag : it comes from me :) )

2024-10-30 16:21 UTC, htagourti commented on identification/speaker_identification.py
> +                vector=spk_embed.flatten(),#.numpy().tolist(),  # Convert to list for Qdrant
qdrant expects a 1D list of embeddings. spk_embed is 3-dimensional [[[1,2,3,...]]]. Flatten() converts it to the expected shape

2024-10-30 16:32 UTC, Jeronymous commented on pyannote/diarization/processing/speakerdiarization.py
> +from identification.speaker_identify import SpeakerIdentifier
You also need to do those modifications in the file `simple/diarization/processing/speakerdiarization.py`
(all the modification of this file).

We have two diarization algo supporting id in the same way : pyannote and "simple diarizer" (which cannot be broken)

2024-10-31 12:21 UTC, Jeronymous commented on identification/speaker_identification.py
> +        return self.qdrant_client and self.qdrant_collection and os.path.isdir(self._FOLDER_WAV)
This has been changed : now on relies on the existence of `self._FOLDER_WAV`

2024-10-31 12:23 UTC, Jeronymous commented on pyannote/requirements.txt
> +qdrant-client
@htagourti This change in requirement is missing for "simple/requirements.txt"

2024-11-19 07:49 UTC, merged